# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: fr


pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
    ## Documentation de https://v2.spacy.io/usage/spacy-101

  - name: SpacyNLP
    model: fr_core_news_sm
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
    pooling: mean

  - name : RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: SpacyEntityExtractor
  - name : ResponseSelector
# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
  - name: RulePolicy
    epochs : 100
  - name: TEDPolicy
    max_history: 5
    epochs: 300 #  Ce paramètre définit le nombre de fois que l’algorithme verra les données d’entraînement (par défaut : ). L’un est égal à une passe vers l’avant et une passe vers
    constrain_similarities: true
  - name : FormPolicy
